---
version: "3"
services:
  datascience:
    image: gnasello/sc-py-env-gpu:2024-05-15.2
    container_name: sc-py-env-gpu
    user: root
    environment:
    - NB_USER=researcher
    - NB_UID=1234
    - NB_GID=1234
    - CHOWN_HOME=yes
    - CHOWN_HOME_OPTS=-R
    - GRANT_SUDO=yes
    ports:
      - 8848:8888
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 'all'
              # count: 1
              # device_ids: ['0', '3']
              capabilities: [gpu]